--------------------------------------------------------
--  File created - Monday-February-17-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DICTIONARY
--------------------------------------------------------
CREATE TABLE "TEMP_MASTEROFFICE" 
   (	"OFFICECODE" VARCHAR2(50 BYTE), 
	"OFFICENAME" VARCHAR2(150 BYTE), 
	"CITY" VARCHAR2(200 BYTE), 
	"REGION" VARCHAR2(100 BYTE), 
	"STATE" VARCHAR2(100 BYTE), 
	"PINCODE" NUMBER, 
	"DICOFFICETYPEID" NUMBER
   );

--------------------------------------------------------
CREATE TABLE "TEMP_STATE" 
   ("REGION" VARCHAR2(100 BYTE), 
	"STATE" NUMBER
   );

--------------------------------------------------------

  CREATE TABLE "DICTIONARY" 
   (	"ID" NUMBER(10,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NAME" VARCHAR2(50 BYTE), 
	"CODE" VARCHAR2(50 BYTE), 
	"VALUE" VARCHAR2(255 BYTE), 
	"ISACTIVE" NUMBER(1,0) DEFAULT 1, 
	"CREATEDBY" VARCHAR2(50 BYTE), 
	"CREATEDDATE" DATE DEFAULT SYSDATE, 
	"MODIFIEDBY" VARCHAR2(50 BYTE), 
	"MODIFIEDDATE" DATE, 
	"ISDELETED" NUMBER(1,0) DEFAULT 0, 
	"DELETEDBY" VARCHAR2(50 BYTE), 
	"DELETEDDATE" DATE, 
	"NUMID" NUMBER(10,0)
   );
--------------------------------------------------------
--  DDL for Table ERRORLOG
--------------------------------------------------------

  CREATE TABLE "ERRORLOG" 
   (	"ERRORID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"PROCEDURENAME" VARCHAR2(100 BYTE), 
	"ERRORMESSAGE" VARCHAR2(4000 BYTE), 
	"ERRORSTACK" CLOB, 
	"ERRORPARAMS" CLOB, 
	"ERRORDATE" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"USERNAME" VARCHAR2(100 BYTE) DEFAULT USER, 
	"METHODNAME" VARCHAR2(200 BYTE)
   );
--------------------------------------------------------
--  DDL for Table LEAVEENTRY
--------------------------------------------------------

  CREATE TABLE "LEAVEENTRY" 
   (	"ID" NUMBER(10,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"EMPLOYEECODE" VARCHAR2(50 BYTE), 
	"DICLEAVETYPEID" NUMBER(10,0), 
	"LEAVEDAYS" NUMBER(10,1), 
	"MONTH" VARCHAR2(20 BYTE), 
	"YEAR" VARCHAR2(20 BYTE), 
	"DICLEAVESTATUSID" NUMBER(10,0), 
	"STATUSCHANGEDBY" VARCHAR2(50 BYTE), 
	"CREATEDDATE" DATE, 
	"CREATEDBY" VARCHAR2(50 BYTE), 
	"MODIFIEDDATE" DATE, 
	"MODIFIEDBY" VARCHAR2(50 BYTE), 
	"COMMENTS" VARCHAR2(500 BYTE), 
	"LEAVEENTRYMAINID" NUMBER(10,0)
   );
--------------------------------------------------------
--  DDL for Table LEAVEENTRYMAIN
--------------------------------------------------------

  CREATE TABLE "LEAVEENTRYMAIN" 
   (	"ID" NUMBER(10,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 10 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"OFFICECODE" VARCHAR2(50 BYTE), 
	"MONTH" VARCHAR2(50 BYTE), 
	"YEAR" VARCHAR2(50 BYTE), 
	"DICSTATUSID" NUMBER, 
	"CREATEDDATE" DATE, 
	"CREATEDBY" VARCHAR2(50 BYTE), 
	"MODIFIEDDATE" DATE, 
	"MODIFIEDBY" VARCHAR2(50 BYTE)
   );
--------------------------------------------------------
--  DDL for Table MASTERADDRESS
--------------------------------------------------------

  CREATE TABLE "MASTERADDRESS" 
   (	"ID" NUMBER(10,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"TABLEKEY" NUMBER(10,0), 
	"TABLENAME" VARCHAR2(50 BYTE), 
	"ADDRESS1" VARCHAR2(150 BYTE), 
	"ADDRESS2" VARCHAR2(150 BYTE), 
	"CITYID" NUMBER(10,0) DEFAULT NULL, 
	"STATEID" NUMBER(10,0), 
	"PIN" VARCHAR2(20 BYTE), 
	"CREATEDDATE" DATE, 
	"CREATEDBY" VARCHAR2(50 BYTE), 
	"MODIFIEDBY" VARCHAR2(50 BYTE), 
	"MODIFIEDDATE" DATE, 
	"DELETEDDATE" DATE, 
	"ISDELETED" NUMBER(1,0) DEFAULT 0, 
	"DELETEDBY" VARCHAR2(50 BYTE) DEFAULT 'System', 
	"OFFICECODE" VARCHAR2(50 BYTE), 
	"EMPLOYEECODE" VARCHAR2(50 BYTE), 
	"CITY" VARCHAR2(100 BYTE) DEFAULT NULL
   );
--------------------------------------------------------
--  DDL for Table MASTERBANK
--------------------------------------------------------

  CREATE TABLE "MASTERBANK" 
   (	"ID" NUMBER(10,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"EMPLOYEECODE" VARCHAR2(50 BYTE), 
	"BANKNAME" VARCHAR2(150 BYTE), 
	"ACCOUNTNUMBER" NVARCHAR2(2000), 
	"IFSCCODE" NVARCHAR2(2000), 
	"BRANCHCODE" VARCHAR2(20 BYTE), 
	"BANKCITYID" NUMBER(10,0), 
	"UANNUMBER" NVARCHAR2(2000), 
	"CREATEDDATE" DATE, 
	"CREATEDBY" VARCHAR2(50 BYTE), 
	"MODIFIEDDATE" DATE, 
	"MODIFIEDBY" VARCHAR2(50 BYTE)
   );
--------------------------------------------------------
--  DDL for Table MASTERCITY
--------------------------------------------------------

  CREATE TABLE "MASTERCITY" 
   (	"ID" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NAME" VARCHAR2(100 BYTE), 
	"MASTERSTATEID" NUMBER, 
	"MASTERCITYCATEGORYID" NUMBER, 
	"ADDITIONALHRA" NUMBER(10,2) DEFAULT 0, 
	"ISACTIVE" NUMBER(1,0) DEFAULT 1, 
	"CREATEDBY" VARCHAR2(50 BYTE), 
	"CREATEDDATE" DATE DEFAULT CURRENT_TIMESTAMP, 
	"MODIFIEDBY" VARCHAR2(50 BYTE), 
	"MODIFIEDDATE" TIMESTAMP (6), 
	"ISDELETED" NUMBER(1,0) DEFAULT 0, 
	"DELETEDBY" VARCHAR2(50 BYTE) DEFAULT NULL, 
	"DELETEDDATE" DATE DEFAULT NULL,                       -- Date and time when the record was deleted, 
	"ISTPTACITY" NUMBER(1,0) DEFAULT 0
   );

   COMMENT ON COLUMN "MASTERCITY"."ID" IS 'Unique identifier for each city';
   COMMENT ON COLUMN "MASTERCITY"."NAME" IS 'Name of the city';
   COMMENT ON COLUMN "MASTERCITY"."MASTERSTATEID" IS 'Reference to the associated state';
   COMMENT ON COLUMN "MASTERCITY"."MASTERCITYCATEGORYID" IS 'Reference to the city category classification';
   COMMENT ON COLUMN "MASTERCITY"."ADDITIONALHRA" IS 'Additional Housing Rent Allowance for the city';
   COMMENT ON COLUMN "MASTERCITY"."CREATEDBY" IS 'User who created the record';
   COMMENT ON COLUMN "MASTERCITY"."CREATEDDATE" IS 'Date and time when the record was created';
   COMMENT ON COLUMN "MASTERCITY"."MODIFIEDBY" IS 'User who last modified the record';
   COMMENT ON COLUMN "MASTERCITY"."MODIFIEDDATE" IS 'Date and time of last modification';
--------------------------------------------------------
--  DDL for Table MASTERCITYCATEGORY
--------------------------------------------------------

  CREATE TABLE "MASTERCITYCATEGORY" 
   (	"ID" NUMBER(10,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NAME" VARCHAR2(100 BYTE), 
	"HRA" NUMBER(10,2), 
	"MINHRA" NUMBER(10,2), 
	"ISACTIVE" NUMBER(1,0) DEFAULT 1, 
	"CREATEDBY" VARCHAR2(50 BYTE), 
	"CREATEDDATE" DATE DEFAULT SYSDATE, 
	"MODIFIEDBY" VARCHAR2(50 BYTE), 
	"MODIFIEDDATE" DATE, 
	"ISDELETED" NUMBER(1,0) DEFAULT 0, 
	"DELETEDBY" VARCHAR2(50 BYTE), 
	"DELETEDDATE" DATE
   );
--------------------------------------------------------
--  DDL for Table MASTERDESIGNATION
--------------------------------------------------------

  CREATE TABLE "MASTERDESIGNATION" 
   (	"ID" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NAME" VARCHAR2(255 BYTE), 
	"ISACTIVE" NUMBER DEFAULT 0, 
	"CREATEDBY" VARCHAR2(50 BYTE), 
	"CREATEDDATE" DATE DEFAULT SYSDATE, 
	"MODIFIEDBY" VARCHAR2(50 BYTE), 
	"MODIFIEDDATE" DATE, 
	"ISDELETED" NUMBER(1,0) DEFAULT 0, 
	"DELETEDBY" VARCHAR2(50 BYTE), 
	"DELETEDDATE" DATE
   );
--------------------------------------------------------
--  DDL for Table MASTEREMPLOYEE
--------------------------------------------------------

  CREATE TABLE "MASTEREMPLOYEE" 
   (	"ID" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"EMPLOYEECODE" VARCHAR2(50 BYTE), 
	"FIRSTNAME" VARCHAR2(100 BYTE), 
	"MIDDLENAME" VARCHAR2(100 BYTE) DEFAULT NULL, 
	"LASTNAME" VARCHAR2(100 BYTE) DEFAULT NULL, 
	"GENDER" NUMBER, 
	"DATEOFBIRTH" DATE, 
	"EMAIL" NVARCHAR2(2000), 
	"MOBILE" NVARCHAR2(2000), 
	"PANNO" NVARCHAR2(2000), 
	"SCHEMETYPE" NUMBER DEFAULT NULL, 
	"OFFICEID" NUMBER, 
	"DATEOFJOINING" DATE, 
	"DATEOFJOININGKVS" DATE, 
	"DESIGNATIONID" NUMBER, 
	"ROLEID" VARCHAR2(50 BYTE) DEFAULT NULL, 
	"LASTINCREMENTDATE" DATE DEFAULT NULL, 
	"NEXTCREMENTDATE" DATE DEFAULT NULL, 
	"LEVELID" NUMBER, 
	"BASICPAY" NUMBER(20,2) DEFAULT NULL, 
	"ISALLOTMENTQUARTER" NUMBER(1,0) DEFAULT 0, 
	"TYPEOFQUARTER" NUMBER DEFAULT 0, 
	"ISADDITIONHRA" NUMBER(1,0) DEFAULT 0, 
	"ADDITIONALHRACITY" NUMBER DEFAULT NULL, 
	"ISHANDICAP" NUMBER(1,0) DEFAULT 0, 
	"DATEOFCERTIFICATE" DATE DEFAULT NULL, 
	"ENTITLEFORDOUBLETA" NUMBER(1,0) DEFAULT 0, 
	"PASSWORD" VARCHAR2(255 BYTE) DEFAULT NULL, 
	"CURRENTDESIGNATIONDATE" DATE DEFAULT NULL, 
	"DOUBLETA" NUMBER DEFAULT 0, 
	"ISACTIVE" NUMBER(1,0) DEFAULT 1, 
	"CREATEDDATE" DATE DEFAULT NULL, 
	"CREATEDBY" VARCHAR2(100 BYTE) DEFAULT NULL, 
	"MODIFIEDDATE" DATE DEFAULT NULL, 
	"MODIFIEDBY" VARCHAR2(100 BYTE) DEFAULT NULL, 
	"ISDELETED" NUMBER(1,0) DEFAULT 0, 
	"DELETEDBY" VARCHAR2(100 BYTE) DEFAULT NULL, 
	"DELETEDEDDATE" DATE DEFAULT NULL, 
	"FULLNAME" VARCHAR2(302 BYTE) GENERATED ALWAYS AS ("FIRSTNAME"||' '||NVL("MIDDLENAME",'')||' '||"LASTNAME") VIRTUAL , 
	"CPFOWNSHARE" NUMBER(10,2) DEFAULT NULL, 
	"GPFOWNSHARE" NUMBER(10,2) DEFAULT NULL, 
	"SLABTYPE" NUMBER DEFAULT NULL
   );
--------------------------------------------------------
--  DDL for Table MASTEREMPLOYEEROLE
--------------------------------------------------------

  CREATE TABLE "MASTEREMPLOYEEROLE" 
   (	"ID" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"EMPLOYEECODE" VARCHAR2(50 BYTE), 
	"ROLEID" NUMBER, 
	"EXPIREDDATE" DATE DEFAULT NULL, 
	"CREATEDBY" VARCHAR2(50 BYTE) DEFAULT NULL, 
	"CREATEDDATE" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"MODIFIEDBY" VARCHAR2(50 BYTE) DEFAULT NULL, 
	"MODIFIEDDATE" TIMESTAMP (6) DEFAULT NULL -- Audit column: Updated Date
   );

   COMMENT ON COLUMN "MASTEREMPLOYEEROLE"."ID" IS 'Unique identifier for the record';
   COMMENT ON COLUMN "MASTEREMPLOYEEROLE"."EMPLOYEECODE" IS 'Code of the Employee';
   COMMENT ON COLUMN "MASTEREMPLOYEEROLE"."ROLEID" IS 'Role identifier';
   COMMENT ON COLUMN "MASTEREMPLOYEEROLE"."EXPIREDDATE" IS 'Expiration date for the role';
   COMMENT ON COLUMN "MASTEREMPLOYEEROLE"."CREATEDBY" IS 'User who created the record';
   COMMENT ON COLUMN "MASTEREMPLOYEEROLE"."CREATEDDATE" IS 'Date and time the record was created';
   COMMENT ON COLUMN "MASTEREMPLOYEEROLE"."MODIFIEDBY" IS 'User who last updated the record';
   COMMENT ON COLUMN "MASTEREMPLOYEEROLE"."MODIFIEDDATE" IS 'Date and time the record was last updated';
--------------------------------------------------------
--  DDL for Table MASTERLEAVE
--------------------------------------------------------

  CREATE TABLE "MASTERLEAVE" 
   (	"ID" NUMBER(10,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"LEAVETYPE" VARCHAR2(50 BYTE), 
	"CAPDAYS" NUMBER(10,0), 
	"DEDUCTIONTYPE" VARCHAR2(50 BYTE), 
	"DEDUCTIONPERC" NUMBER(10,0), 
	"CREATEDDATE" DATE, 
	"CREATEDBY" VARCHAR2(50 BYTE), 
	"MODIFIEDDATE" DATE, 
	"MODIFIEDBY" VARCHAR2(50 BYTE), 
	"DELETEDBY" VARCHAR2(255 BYTE), 
	"ISDELETED" NUMBER DEFAULT 0, 
	"BASICPAYDED" NUMBER(10,4), 
	"TADED" NUMBER(10,4), 
	"DADED" NUMBER(10,4), 
	"ISACTIVE" NUMBER(1,0) DEFAULT 1, 
	"DELETEDDATE" DATE
   );
--------------------------------------------------------
--  DDL for Table MASTERLEVEL
--------------------------------------------------------

  CREATE TABLE "MASTERLEVEL" 
   (	"ID" NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"LEVELNAME" VARCHAR2(50 BYTE), 
	"CREATEDDATE" DATE, 
	"CREATEDBY" VARCHAR2(50 BYTE), 
	"MODIFIEDDATE" DATE, 
	"MODIFIEDBY" VARCHAR2(50 BYTE), 
	"ISACTIVE" NUMBER(1,0) DEFAULT 1, 
	"ISDELETED" NUMBER(1,0) DEFAULT 0, 
	"DELETEDBY" VARCHAR2(50 BYTE), 
	"DELETEDTIME" DATE, 
	"NUMID" NUMBER(10,0) DEFAULT 0
   );
--------------------------------------------------------
--  DDL for Table MASTERLEVELBASICPAY
--------------------------------------------------------

  CREATE TABLE "MASTERLEVELBASICPAY" 
   (	"ID" NUMBER(10,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"LEVELID" NUMBER(10,0), 
	"PAYSCALE" VARCHAR2(50 BYTE), 
	"BASICPAY" NUMBER(10,2), 
	"CREATEDDATE" DATE, 
	"CREATEDBY" VARCHAR2(50 BYTE), 
	"MODIFIEDDATE" DATE, 
	"MODIFIEDBY" VARCHAR2(50 BYTE), 
	"ISACTIVE" NUMBER(1,0) DEFAULT 1, 
	"ISDELETED" NUMBER(1,0) DEFAULT 0, 
	"DELETEDBY" VARCHAR2(50 BYTE), 
	"DELETEDTIME" DATE
   );
--------------------------------------------------------
--  DDL for Table MASTERMENU
--------------------------------------------------------

  CREATE TABLE "MASTERMENU" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NAME" VARCHAR2(100 BYTE), 
	"ICON" VARCHAR2(100 BYTE), 
	"URL" VARCHAR2(200 BYTE), 
	"MODULEID" NUMBER DEFAULT NULL, 
	"SORTORDER" NUMBER DEFAULT NULL, 
	"ISACTIVE" NUMBER(1,0) DEFAULT NULL, 
	"ISMENU" NUMBER(1,0) DEFAULT NULL, 
	"PARENTID" NUMBER DEFAULT NULL, 
	"CREATEDBY" VARCHAR2(100 BYTE) DEFAULT NULL, 
	"CREATEDDATE" DATE DEFAULT NULL, 
	"MODIFIEDBY" VARCHAR2(100 BYTE) DEFAULT NULL, 
	"MODIFIEDDATE" DATE DEFAULT NULL, 
	"CONTROLLER" VARCHAR2(100 BYTE), 
	"ISDISPLAY" NUMBER
   );
--------------------------------------------------------
--  DDL for Table MASTERMODULE
--------------------------------------------------------

  CREATE TABLE "MASTERMODULE" 
   (	"ID" NUMBER(10,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NAME" VARCHAR2(100 BYTE), 
	"SORTORDER" NUMBER(10,0), 
	"ISACTIVE" NUMBER(1,0), 
	"CREATEDBY" VARCHAR2(50 BYTE), 
	"CREATEDDATE" DATE, 
	"MODIFIEDBY" VARCHAR2(50 BYTE), 
	"MODIFIEDDATE" DATE
   );
--------------------------------------------------------
--  DDL for Table MASTEROFFICE
--------------------------------------------------------

  CREATE TABLE "MASTEROFFICE" 
   (	"ID" NUMBER(10,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"OFFICECODE" VARCHAR2(50 BYTE), 
	"OFFICENAME" VARCHAR2(150 BYTE), 
	"OFFICETYPEID" NUMBER, 
	"EMAIL" VARCHAR2(50 BYTE), 
	"MOBILENO" VARCHAR2(50 BYTE), 
	"TELEPHONENUMBER" VARCHAR2(50 BYTE), 
	"WEBADDRESS" VARCHAR2(150 BYTE), 
	"ISACTIVE" NUMBER(*,0), 
	"CREATEDDATE" DATE, 
	"CREATEDBY" VARCHAR2(50 BYTE), 
	"MODIFIEDDATE" DATE, 
	"MODIFIEDBY" VARCHAR2(50 BYTE), 
	"DELETEDBY" VARCHAR2(255 BYTE), 
	"ISDELETED" NUMBER DEFAULT 0, 
	"PROFESSIONALTAX" VARCHAR2(50 BYTE), 
	"DELETEDDATE" DATE, 
	"PARENTOFFICEID" NUMBER, 
	"DICOFFICETYPEID" NUMBER, 
	"BANKNAME" VARCHAR2(255 BYTE), 
	"BANKACCOUNTNO" VARCHAR2(20 BYTE), 
	"IFSCCODE" VARCHAR2(20 BYTE), 
	"BRANCHNAME" VARCHAR2(255 BYTE)
   );
--------------------------------------------------------
--  DDL for Table MASTEROFFICE_BACKUP
--------------------------------------------------------

  CREATE TABLE "MASTEROFFICE_BACKUP" 
   (	"ID" NUMBER(10,0), 
	"OFFICECODE" VARCHAR2(50 BYTE), 
	"OFFICENAME" VARCHAR2(150 BYTE), 
	"OFFICETYPEID" NUMBER, 
	"EMAIL" VARCHAR2(50 BYTE), 
	"MOBILENO" VARCHAR2(50 BYTE), 
	"TELEPHONENUMBER" VARCHAR2(50 BYTE), 
	"WEBADDRESS" VARCHAR2(150 BYTE), 
	"ISACTIVE" NUMBER(*,0), 
	"CREATEDDATE" DATE, 
	"CREATEDBY" VARCHAR2(50 BYTE), 
	"MODIFIEDDATE" DATE, 
	"MODIFIEDBY" VARCHAR2(50 BYTE), 
	"DELETEDBY" VARCHAR2(255 BYTE), 
	"ISDELETED" NUMBER, 
	"PROFESSIONALTAX" VARCHAR2(50 BYTE), 
	"DELETEDDATE" DATE, 
	"PARENTOFFICEID" NUMBER, 
	"DICOFFICETYPEID" NUMBER
   );
--------------------------------------------------------
--  DDL for Table MASTEROFFICE_BACKUP_02_04_2024
--------------------------------------------------------

  CREATE TABLE "MASTEROFFICE_BACKUP_02_04_2024" 
   (	"ID" NUMBER(10,0), 
	"OFFICECODE" VARCHAR2(50 BYTE), 
	"OFFICENAME" VARCHAR2(150 BYTE), 
	"OFFICETYPEID" NUMBER, 
	"EMAIL" VARCHAR2(50 BYTE), 
	"MOBILENO" VARCHAR2(50 BYTE), 
	"TELEPHONENUMBER" VARCHAR2(50 BYTE), 
	"WEBADDRESS" VARCHAR2(150 BYTE), 
	"ISACTIVE" NUMBER(*,0), 
	"CREATEDDATE" DATE, 
	"CREATEDBY" VARCHAR2(50 BYTE), 
	"MODIFIEDDATE" DATE, 
	"MODIFIEDBY" VARCHAR2(50 BYTE), 
	"DELETEDBY" VARCHAR2(255 BYTE), 
	"ISDELETED" NUMBER, 
	"PROFESSIONALTAX" VARCHAR2(50 BYTE), 
	"DELETEDDATE" DATE, 
	"PARENTOFFICEID" NUMBER, 
	"DICOFFICETYPEID" NUMBER
   );
--------------------------------------------------------
--  DDL for Table MASTEROFFICETYPE
--------------------------------------------------------

  CREATE TABLE "MASTEROFFICETYPE" 
   (	"ID" NUMBER(10,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 10 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"TYPE" VARCHAR2(50 BYTE), 
	"PARENTID" NUMBER, 
	"CREATEDDATE" DATE, 
	"CREATEDBY" VARCHAR2(50 BYTE), 
	"MODIFIEDDATE" DATE, 
	"MODIFIEDBY" VARCHAR2(50 BYTE)
   );
--------------------------------------------------------
--  DDL for Table MASTERPERMISSION
--------------------------------------------------------

  CREATE TABLE "MASTERPERMISSION" 
   (	"ID" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"CODE" VARCHAR2(50 BYTE) DEFAULT NULL, 
	"NAME" VARCHAR2(100 BYTE) DEFAULT NULL, 
	"MENUID" NUMBER DEFAULT NULL, 
	"ISACTIVE" NUMBER DEFAULT 1, 
	"CREATEDBY" VARCHAR2(50 BYTE) DEFAULT NULL, 
	"CREATEDDATE" DATE DEFAULT SYSDATE, 
	"MODIFIEDBY" VARCHAR2(50 BYTE) DEFAULT NULL, 
	"MODIFIEDDATE" DATE DEFAULT NULL, 
	"ISDELETED" NUMBER DEFAULT 0
   );
--------------------------------------------------------
--  DDL for Table MASTERROLE
--------------------------------------------------------

  CREATE TABLE "MASTERROLE" 
   (	"ID" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ROLENAME" VARCHAR2(250 BYTE), 
	"ISACTIVE" NUMBER(1,0) DEFAULT 1, 
	"CREATEDBY" VARCHAR2(50 BYTE), 
	"CREATEDDATE" DATE DEFAULT SYSDATE, 
	"MODIFIEDBY" VARCHAR2(50 BYTE), 
	"MODIFIEDDATE" DATE, 
	"ISDELETED" NUMBER(1,0) DEFAULT 0, 
	"DELETEDBY" VARCHAR2(255 BYTE), 
	"DELETEDDATE" DATE, 
	"LEVELBY" NUMBER, 
	"CODE" VARCHAR2(5 BYTE)
   );
--------------------------------------------------------
--  DDL for Table MASTERROLEPERMISSION
--------------------------------------------------------

  CREATE TABLE "MASTERROLEPERMISSION" 
   (	"ID" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ROLEID" NUMBER DEFAULT NULL, 
	"PERMISSIONID" NUMBER DEFAULT NULL, 
	"ISACTIVE" NUMBER DEFAULT 1, 
	"CREATEDBY" VARCHAR2(50 BYTE) DEFAULT NULL, 
	"CREATEDDATE" DATE DEFAULT SYSDATE, 
	"MODIFIEDBY" VARCHAR2(50 BYTE) DEFAULT NULL, 
	"MODIFIEDDATE" DATE DEFAULT NULL, 
	"ISDELETED" NUMBER DEFAULT 0
   );
--------------------------------------------------------
--  DDL for Table MASTERSTATE
--------------------------------------------------------

  CREATE TABLE "MASTERSTATE" 
   (	"ID" NUMBER(10,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 10 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"CODE" VARCHAR2(20 BYTE), 
	"STATENAME" NVARCHAR2(100), 
	"ISACTIVE" NUMBER(*,0), 
	"CREATEDDATE" DATE, 
	"CREATEDBY" VARCHAR2(50 BYTE), 
	"MODIFIEDDATE" DATE, 
	"MODIFIEDBY" VARCHAR2(50 BYTE)
   );
--------------------------------------------------------
--  DDL for Table MASTERTA
--------------------------------------------------------

  CREATE TABLE "MASTERTA" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"PLFROM" NUMBER, 
	"PLTO" NUMBER, 
	"NORMALCITY" NUMBER(18,2), 
	"TPTACITY" NUMBER(18,2), 
	"CREATEDBY" VARCHAR2(50 BYTE), 
	"CREATEDDATE" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"MODIFIEDBY" VARCHAR2(50 BYTE), 
	"MODIFIEDDATE" TIMESTAMP (6), 
	"ISACTIVE" NUMBER(1,0) DEFAULT 1, 
	"ISDELETED" NUMBER(1,0) DEFAULT 0, 
	"DELETEDBY" VARCHAR2(50 BYTE), 
	"DELETEDDATE" TIMESTAMP (6)
   );
--------------------------------------------------------
--  DDL for Table MASTERTAXSLAB
--------------------------------------------------------

  CREATE TABLE "MASTERTAXSLAB" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"SLAB_TYPE_ID" NUMBER, 
	"MIN_INCOME" NUMBER(15,2), 
	"MAX_INCOME" NUMBER(15,2), 
	"TAX_RATE" NUMBER(5,2), 
	"CREATEDBY" VARCHAR2(50 BYTE), 
	"CREATEDDATE" DATE DEFAULT SYSDATE, 
	"MODIFIEDBY" VARCHAR2(50 BYTE), 
	"MODIFIEDDATE" DATE
   );
--------------------------------------------------------
--  DDL for Table PAYBILLALLOWANCE
--------------------------------------------------------

  CREATE TABLE "PAYBILLALLOWANCE" 
   (	"ID" NUMBER(20,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"PAYBILLEMPLOYEEID" NUMBER(20,0), 
	"DEPUTATIONALLOWANCE" NUMBER(20,2) DEFAULT 0, 
	"DEARNESSALLOWANCE" NUMBER(20,2), 
	"TRANSPORTALLOWANCE" NUMBER(20,2), 
	"DAONTRANSPORTALL0WANCE" NUMBER(20,2), 
	"HOUSERENTALLOWANCEDHRA" NUMBER(20,2) DEFAULT 0, 
	"NPSMGTSHARE" NUMBER(20,2) DEFAULT 0, 
	"CPFMGTSHARE" NUMBER(20,2) DEFAULT 0, 
	"CASHHANDLINGTREASURYALLOWANCE" NUMBER(20,2) DEFAULT 0, 
	"HIGHALTITUDEALLOWANCE" NUMBER(20,2) DEFAULT 0, 
	"HARDAREAALLOWANCE" NUMBER(20,2) DEFAULT 0, 
	"ISLANDSPECIALDUTYALLOWANCE" NUMBER(20,2) DEFAULT 0, 
	"SPECIALDUTYALLOWANCE" NUMBER(20,2) DEFAULT 0, 
	"TOUGHLOCATIONALLOWANCE1" NUMBER(20,2) DEFAULT 0, 
	"TOUGHLOCATIONALLOWANCE2" NUMBER(20,2) DEFAULT 0, 
	"TOUGHLOCATIONALLOWANCE3" NUMBER(20,2) DEFAULT 0, 
	"SECONDSHIFTALLOWANCE" NUMBER(20,2) DEFAULT 0, 
	"LSANDPCPROJECTKVS" NUMBER(20,2) DEFAULT 0, 
	"OTHERALLOWANCE" NUMBER(20,2) DEFAULT 0, 
	"DRESSALLOWANCE" NUMBER(20,2) DEFAULT 0, 
	"CREATEDDATE" DATE, 
	"CREATEDBY" VARCHAR2(50 BYTE), 
	"MODIFIEDDATE" DATE, 
	"MODIFIEDBY" VARCHAR2(20 BYTE), 
	"ISDELETED" NUMBER(1,0), 
	"DELETEDBY" VARCHAR2(50 BYTE), 
	"DELETEDDATE" DATE, 
	"ADDITIONALHRA" NUMBER(*,0)
   );
--------------------------------------------------------
--  DDL for Table PAYBILLDEDUCTION
--------------------------------------------------------

  CREATE TABLE "PAYBILLDEDUCTION" 
   (	"ID" NUMBER(20,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"PAYBILLEMPLOYEEID" NUMBER(20,0), 
	"INCOMETAX" NUMBER(20,2) DEFAULT 0, 
	"PROFESSIONALTAX" NUMBER(20,2) DEFAULT 0, 
	"LICENCEFEEOUTSIDEAGENCY" NUMBER(20,2) DEFAULT 0, 
	"ELECTRICWATERCHARGESOUTSIDEAGENCY" NUMBER(20,2) DEFAULT 0, 
	"NPSOWNSHARE" NUMBER(20,2) DEFAULT 0, 
	"NPSMGTSHARE" NUMBER(20,2) DEFAULT 0, 
	"COOPSOCIETY" NUMBER(20,2) DEFAULT 0, 
	"CONVADVINTERESTRECOVERY" NUMBER(20,2) DEFAULT 0, 
	"CAIRINSTALLMENTNO" NUMBER(20,0) DEFAULT 0, 
	"HOUSEBUILDINGADVANCEINTEREST" NUMBER(20,2) DEFAULT 0, 
	"HBAIINSTALLMENTNO" NUMBER(20,0) DEFAULT 0, 
	"PRIMEMINISTERCARESFUND" NUMBER(20,2) DEFAULT 0, 
	"OTHERREMITTANCES" NUMBER(20,2) DEFAULT 0, 
	"GPFRECOVERY" NUMBER(20,2) DEFAULT 0, 
	"GPFADVANCERECOVERY" NUMBER(20,2) DEFAULT 0, 
	"GPFINSTALMENTNO" NUMBER(20,0) DEFAULT 0, 
	"CPFRECOVERYOWNSHARE" NUMBER(20,2) DEFAULT 0, 
	"CPFRECOVERYMGTSHARE" NUMBER(20,2) DEFAULT 0, 
	"CPFADVRECOVERY" NUMBER(20,2) DEFAULT 0, 
	"CPFINSTALLMENTNO" NUMBER(20,0) DEFAULT 0, 
	"KVSEMPLOYEESWELFARESCHEME" NUMBER(20,2) DEFAULT 0, 
	"LSANDPCPROJECTKVS" NUMBER(20,2) DEFAULT 0, 
	"HPLRECOVERY" NUMBER(20,2) DEFAULT 0, 
	"LICENCEFEESKVSBUILDING" NUMBER(20,2) DEFAULT 0, 
	"ELECTRICWATERCHARGES" NUMBER(20,2) DEFAULT 0, 
	"RECOFOVERPAYMENT" NUMBER(20,2) DEFAULT 0, 
	"CGHSRECOVERY" NUMBER(20,2) DEFAULT 0, 
	"OTHERDEDUCTIONS" NUMBER(20,2) DEFAULT 0, 
	"CREATEDDATE" DATE, 
	"CREATEDBY" VARCHAR2(50 BYTE), 
	"MODIFIEDDATE" DATE, 
	"MODIFIEDBY" VARCHAR2(20 BYTE), 
	"ISDELETED" NUMBER(1,0), 
	"DELETEDBY" VARCHAR2(50 BYTE), 
	"DELETEDDATE" DATE
   );
--------------------------------------------------------
--  DDL for Table PAYBILLEMPLOYEE
--------------------------------------------------------

  CREATE TABLE "PAYBILLEMPLOYEE" 
   (	"ID" NUMBER(20,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"PAYBILLMAINID" NUMBER(20,0), 
	"EMPLOYEECODE" VARCHAR2(50 BYTE), 
	"EMPLOYEENAME" VARCHAR2(100 BYTE), 
	"EMPLOYEEDESIGNATION" VARCHAR2(100 BYTE), 
	"LEVELNAME" VARCHAR2(50 BYTE), 
	"NUMBEROFPOSTSANCTIONED" NUMBER(10,0), 
	"STAFFINPOSITION" NUMBER(10,0), 
	"TOTALDAYS" NUMBER(10,0), 
	"TOTALPRESENTDAYS" NUMBER(5,1), 
	"BASICPAY" NUMBER(20,0), 
	"TOTALALLOWANCE" NUMBER(20,2), 
	"TOTALDEDUCTION" NUMBER(20,2), 
	"FINALAMOUNT" NUMBER(20,2) DEFAULT 0, 
	"DICSTATUSID" NUMBER(10,0), 
	"CREATEDDATE" DATE, 
	"CREATEDBY" VARCHAR2(50 BYTE), 
	"MODIFIEDDATE" DATE, 
	"MODIFIEDBY" VARCHAR2(20 BYTE), 
	"ISDELETED" NUMBER DEFAULT 0, 
	"DELETEDBY" VARCHAR2(50 BYTE), 
	"DELETEDDATE" DATE, 
	"DICROSTATUSID" NUMBER(10,0), 
	"DICHOSTATUSID" NUMBER(10,0), 
	"COMMENTS" VARCHAR2(100 BYTE), 
	"ROCOMMENTS" VARCHAR2(100 BYTE), 
	"HOCOMMENTS" VARCHAR2(100 BYTE)
   );
--------------------------------------------------------
--  DDL for Table PAYBILLMAIN
--------------------------------------------------------

  CREATE TABLE "PAYBILLMAIN" 
   (	"ID" NUMBER(10,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"OFFICECODE" VARCHAR2(500 BYTE), 
	"MONTH" VARCHAR2(20 BYTE), 
	"YEAR" VARCHAR2(20 BYTE), 
	"DICSTATUSID" NUMBER(10,0), 
	"DICHOSTATUSID" NUMBER(10,0), 
	"CREATEDDATE" DATE, 
	"CREATEDBY" VARCHAR2(50 BYTE), 
	"MODIFIEDDATE" DATE, 
	"MODIFIEDBY" VARCHAR2(20 BYTE), 
	"ISDELETED" NUMBER(1,0), 
	"DELETEDBY" VARCHAR2(50 BYTE), 
	"DELETEDDATE" DATE, 
	"GROSSAMOUNT" NUMBER(10,3), 
	"DEDUCTIONAMOUNT" NUMBER(10,3), 
	"NETAMOUNT" NUMBER(10,3), 
	"DICROSTATUSID" NUMBER(10,0)
   );
--------------------------------------------------------
--  DDL for Index DICTIONARY_CODE_VALUE_IDX
--------------------------------------------------------

  CREATE UNIQUE INDEX "DICTIONARY_CODE_VALUE_IDX" ON "DICTIONARY" (LOWER("CODE"), LOWER("VALUE"));
--------------------------------------------------------
--  DDL for Index UC_CODE_VALUE_DICTIONARY
--------------------------------------------------------

  CREATE UNIQUE INDEX "UC_CODE_VALUE_DICTIONARY" ON "DICTIONARY" ("CODE", "VALUE");
--------------------------------------------------------
--  DDL for Index SYS_C007699
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C007699" ON "DICTIONARY" ("ID");
--------------------------------------------------------
--  DDL for Index SYS_C008016
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C008016" ON "ERRORLOG" ("ERRORID");
--------------------------------------------------------
--  DDL for Index SYS_C007529
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C007529" ON "LEAVEENTRY" ("ID");
--------------------------------------------------------
--  DDL for Index SYS_C007833
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C007833" ON "LEAVEENTRYMAIN" ("ID");
--------------------------------------------------------
--  DDL for Index SYS_C007562
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C007562" ON "MASTERADDRESS" ("ID");
--------------------------------------------------------
--  DDL for Index MASTERBANK_EMPLOYEECODE_IDX
--------------------------------------------------------

  CREATE UNIQUE INDEX "MASTERBANK_EMPLOYEECODE_IDX" ON "MASTERBANK" (LOWER("EMPLOYEECODE"));
--------------------------------------------------------
--  DDL for Index SYS_C007676
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C007676" ON "MASTERBANK" ("ID");
--------------------------------------------------------
--  DDL for Index SYS_C007677
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C007677" ON "MASTERBANK" ("EMPLOYEECODE");
--------------------------------------------------------
--  DDL for Index MASTERCITY_NAME_IDX
--------------------------------------------------------

  CREATE UNIQUE INDEX "MASTERCITY_NAME_IDX" ON "MASTERCITY" (LOWER("NAME"));
--------------------------------------------------------
--  DDL for Index UC_CITYNAME
--------------------------------------------------------

  CREATE UNIQUE INDEX "UC_CITYNAME" ON "MASTERCITY" ("NAME");
--------------------------------------------------------
--  DDL for Index SYS_C007618
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C007618" ON "MASTERCITY" ("ID");
--------------------------------------------------------
--  DDL for Index MASTERCITYCATEGORY_NAME_IDX
--------------------------------------------------------

  CREATE UNIQUE INDEX "MASTERCITYCATEGORY_NAME_IDX" ON "MASTERCITYCATEGORY" (LOWER("NAME"));
--------------------------------------------------------
--  DDL for Index SYS_C007633
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C007633" ON "MASTERCITYCATEGORY" ("ID");
--------------------------------------------------------
--  DDL for Index UC_MASTERCITYCATEGORY
--------------------------------------------------------

  CREATE UNIQUE INDEX "UC_MASTERCITYCATEGORY" ON "MASTERCITYCATEGORY" ("NAME");
--------------------------------------------------------
--  DDL for Index CN_MASTERDESIGNATION_NAME_IDX
--------------------------------------------------------

  CREATE UNIQUE INDEX "CN_MASTERDESIGNATION_NAME_IDX" ON "MASTERDESIGNATION" (LOWER("NAME"));
--------------------------------------------------------
--  DDL for Index SYS_C007624
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C007624" ON "MASTERDESIGNATION" ("ID");
--------------------------------------------------------
--  DDL for Index UQ_EMPLOYEE_EMPLOYEECODE
--------------------------------------------------------

  CREATE UNIQUE INDEX "UQ_EMPLOYEE_EMPLOYEECODE" ON "MASTEREMPLOYEE" ("EMPLOYEECODE");
--------------------------------------------------------
--  DDL for Index UC_PAN
--------------------------------------------------------

  CREATE UNIQUE INDEX "UC_PAN" ON "MASTEREMPLOYEE" ("PANNO");
--------------------------------------------------------
--  DDL for Index MASTEREMPLOYEE_PANNO_IDX
--------------------------------------------------------

  CREATE UNIQUE INDEX "MASTEREMPLOYEE_PANNO_IDX" ON "MASTEREMPLOYEE" (LOWER("PANNO"));
--------------------------------------------------------
--  DDL for Index UQ_MASTEREMPLOYEE_EMAIL
--------------------------------------------------------

  CREATE UNIQUE INDEX "UQ_MASTEREMPLOYEE_EMAIL" ON "MASTEREMPLOYEE" ("EMAIL");
--------------------------------------------------------
--  DDL for Index UQ_MASTEREMPLOYEE_MOBILE
--------------------------------------------------------

  CREATE UNIQUE INDEX "UQ_MASTEREMPLOYEE_MOBILE" ON "MASTEREMPLOYEE" ("MOBILE");
--------------------------------------------------------
--  DDL for Index SYS_C007722
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C007722" ON "MASTEREMPLOYEE" ("ID");
--------------------------------------------------------
--  DDL for Index SYS_C007776
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C007776" ON "MASTEREMPLOYEEROLE" ("ID");
--------------------------------------------------------
--  DDL for Index SYS_C007506
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C007506" ON "MASTERLEAVE" ("ID");
--------------------------------------------------------
--  DDL for Index MASTERLEAVE_LEAVETYPE_IDX
--------------------------------------------------------

  CREATE UNIQUE INDEX "MASTERLEAVE_LEAVETYPE_IDX" ON "MASTERLEAVE" (LOWER("LEAVETYPE"));
--------------------------------------------------------
--  DDL for Index UNIQUE_LEAVE
--------------------------------------------------------

  CREATE UNIQUE INDEX "UNIQUE_LEAVE" ON "MASTERLEAVE" ("LEAVETYPE");
--------------------------------------------------------
--  DDL for Index MASTERLEVEL_LEVELNAME_IDX
--------------------------------------------------------

  CREATE UNIQUE INDEX "MASTERLEVEL_LEVELNAME_IDX" ON "MASTERLEVEL" (LOWER("LEVELNAME"));
--------------------------------------------------------
--  DDL for Index UC_MASTERLEVEL
--------------------------------------------------------

  CREATE UNIQUE INDEX "UC_MASTERLEVEL" ON "MASTERLEVEL" ("LEVELNAME");
--------------------------------------------------------
--  DDL for Index MASTERLEVELBASICPAY_LEVELID_PAYSCALE_BASICPAY_IDX
--------------------------------------------------------

  CREATE UNIQUE INDEX "MASTERLEVELBASICPAY_LEVELID_PAYSCALE_BASICPAY_IDX" ON "MASTERLEVELBASICPAY" (LOWER(TO_CHAR("LEVELID")), LOWER("PAYSCALE"), LOWER(TO_CHAR("BASICPAY")));
--------------------------------------------------------
--  DDL for Index UC_MASTERLEVELBASICPAY
--------------------------------------------------------

  CREATE UNIQUE INDEX "UC_MASTERLEVELBASICPAY" ON "MASTERLEVELBASICPAY" ("LEVELID", "PAYSCALE", "BASICPAY");
--------------------------------------------------------
--  DDL for Index SYS_C007822
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C007822" ON "MASTERMENU" ("ID");
--------------------------------------------------------
--  DDL for Index SYS_C007820
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C007820" ON "MASTERMODULE" ("ID");
--------------------------------------------------------
--  DDL for Index MASTEROFFICE_OFFICECODE_IDX
--------------------------------------------------------

  CREATE UNIQUE INDEX "MASTEROFFICE_OFFICECODE_IDX" ON "MASTEROFFICE" (LOWER("OFFICECODE"));
--------------------------------------------------------
--  DDL for Index OFFICECODE_UNIQUE
--------------------------------------------------------

  CREATE UNIQUE INDEX "OFFICECODE_UNIQUE" ON "MASTEROFFICE" ("OFFICECODE");
--------------------------------------------------------
--  DDL for Index MASTEROFFICE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MASTEROFFICE_PK" ON "MASTEROFFICE" ("ID");
--------------------------------------------------------
--  DDL for Index MASTEROFFICETYPE_TYPE_IDX
--------------------------------------------------------

  CREATE UNIQUE INDEX "MASTEROFFICETYPE_TYPE_IDX" ON "MASTEROFFICETYPE" (LOWER("TYPE"));
--------------------------------------------------------
--  DDL for Index SYS_C007544
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C007544" ON "MASTEROFFICETYPE" ("ID");
--------------------------------------------------------
--  DDL for Index SYS_C007545
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C007545" ON "MASTEROFFICETYPE" ("TYPE");
--------------------------------------------------------
--  DDL for Index PK_MASTERPERMISSION
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_MASTERPERMISSION" ON "MASTERPERMISSION" ("ID");
--------------------------------------------------------
--  DDL for Index MASTERROLE_ROLENAME_IDX
--------------------------------------------------------

  CREATE UNIQUE INDEX "MASTERROLE_ROLENAME_IDX" ON "MASTERROLE" (LOWER("ROLENAME"));
--------------------------------------------------------
--  DDL for Index ROLENAME_UNIQUE
--------------------------------------------------------

  CREATE UNIQUE INDEX "ROLENAME_UNIQUE" ON "MASTERROLE" ("ROLENAME");
--------------------------------------------------------
--  DDL for Index SYS_C007597
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C007597" ON "MASTERROLE" ("ID");
--------------------------------------------------------
--  DDL for Index PK_MASTERMENUROLEPERMISSION
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_MASTERMENUROLEPERMISSION" ON "MASTERROLEPERMISSION" ("ID");
--------------------------------------------------------
--  DDL for Index UC_STATENAME_MASTERSTATE
--------------------------------------------------------

  CREATE UNIQUE INDEX "UC_STATENAME_MASTERSTATE" ON "MASTERSTATE" ("STATENAME");
--------------------------------------------------------
--  DDL for Index MASTERSTATE_CODE_IDX
--------------------------------------------------------

  CREATE UNIQUE INDEX "MASTERSTATE_CODE_IDX" ON "MASTERSTATE" (LOWER("CODE"));
--------------------------------------------------------
--  DDL for Index SYS_C007653
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C007653" ON "MASTERSTATE" ("ID");
--------------------------------------------------------
--  DDL for Index SYS_C007654
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C007654" ON "MASTERSTATE" ("CODE");
--------------------------------------------------------
--  DDL for Index SYS_C008144
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C008144" ON "MASTERTA" ("ID");
--------------------------------------------------------
--  DDL for Index SYS_C008173
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C008173" ON "MASTERTAXSLAB" ("ID");
--------------------------------------------------------
--  DDL for Index SYS_C007974
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C007974" ON "PAYBILLALLOWANCE" ("ID");
--------------------------------------------------------
--  DDL for Index SYS_C008006
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C008006" ON "PAYBILLDEDUCTION" ("ID");
--------------------------------------------------------
--  DDL for Index SYS_C007951
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C007951" ON "PAYBILLEMPLOYEE" ("ID");
--------------------------------------------------------
--  DDL for Index PAYBILLMAIN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PAYBILLMAIN_PK" ON "PAYBILLMAIN" ("ID");
--------------------------------------------------------
--  Constraints for Table DICTIONARY
--------------------------------------------------------

  ALTER TABLE "DICTIONARY" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DICTIONARY" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "DICTIONARY" MODIFY ("CODE" NOT NULL ENABLE);
  ALTER TABLE "DICTIONARY" MODIFY ("VALUE" NOT NULL ENABLE);
  ALTER TABLE "DICTIONARY" ADD PRIMARY KEY ("ID");
  ALTER TABLE "DICTIONARY" ADD CONSTRAINT "UC_CODE_VALUE_DICTIONARY" UNIQUE ("CODE", "VALUE");
--------------------------------------------------------
--  Constraints for Table ERRORLOG
--------------------------------------------------------

  ALTER TABLE "ERRORLOG" MODIFY ("ERRORID" NOT NULL ENABLE);
  ALTER TABLE "ERRORLOG" ADD PRIMARY KEY ("ERRORID");
--------------------------------------------------------
--  Constraints for Table LEAVEENTRY
--------------------------------------------------------

  ALTER TABLE "LEAVEENTRY" MODIFY ("LEAVEENTRYMAINID" NOT NULL ENABLE);
  ALTER TABLE "LEAVEENTRY" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "LEAVEENTRY" MODIFY ("EMPLOYEECODE" NOT NULL ENABLE);
  ALTER TABLE "LEAVEENTRY" MODIFY ("DICLEAVETYPEID" NOT NULL ENABLE);
  ALTER TABLE "LEAVEENTRY" MODIFY ("LEAVEDAYS" NOT NULL ENABLE);
  ALTER TABLE "LEAVEENTRY" MODIFY ("MONTH" NOT NULL ENABLE);
  ALTER TABLE "LEAVEENTRY" MODIFY ("YEAR" NOT NULL ENABLE);
  ALTER TABLE "LEAVEENTRY" MODIFY ("CREATEDDATE" NOT NULL ENABLE);
  ALTER TABLE "LEAVEENTRY" MODIFY ("CREATEDBY" NOT NULL ENABLE);
  ALTER TABLE "LEAVEENTRY" ADD PRIMARY KEY ("ID");
--------------------------------------------------------
--  Constraints for Table LEAVEENTRYMAIN
--------------------------------------------------------

  ALTER TABLE "LEAVEENTRYMAIN" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "LEAVEENTRYMAIN" MODIFY ("OFFICECODE" NOT NULL ENABLE);
  ALTER TABLE "LEAVEENTRYMAIN" MODIFY ("MONTH" NOT NULL ENABLE);
  ALTER TABLE "LEAVEENTRYMAIN" MODIFY ("YEAR" NOT NULL ENABLE);
  ALTER TABLE "LEAVEENTRYMAIN" MODIFY ("CREATEDDATE" NOT NULL ENABLE);
  ALTER TABLE "LEAVEENTRYMAIN" MODIFY ("CREATEDBY" NOT NULL ENABLE);
  ALTER TABLE "LEAVEENTRYMAIN" ADD PRIMARY KEY ("ID");
--------------------------------------------------------
--  Constraints for Table MASTERADDRESS
--------------------------------------------------------

  ALTER TABLE "MASTERADDRESS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "MASTERADDRESS" MODIFY ("TABLEKEY" NOT NULL ENABLE);
  ALTER TABLE "MASTERADDRESS" MODIFY ("TABLENAME" NOT NULL ENABLE);
  ALTER TABLE "MASTERADDRESS" MODIFY ("STATEID" NOT NULL ENABLE);
  ALTER TABLE "MASTERADDRESS" MODIFY ("CREATEDDATE" NOT NULL ENABLE);
  ALTER TABLE "MASTERADDRESS" MODIFY ("CREATEDBY" NOT NULL ENABLE);
  ALTER TABLE "MASTERADDRESS" ADD PRIMARY KEY ("ID");
  ALTER TABLE "MASTERADDRESS" MODIFY ("DELETEDBY" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MASTERBANK
--------------------------------------------------------

  ALTER TABLE "MASTERBANK" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "MASTERBANK" MODIFY ("EMPLOYEECODE" NOT NULL ENABLE);
  ALTER TABLE "MASTERBANK" MODIFY ("BANKNAME" NOT NULL ENABLE);
  ALTER TABLE "MASTERBANK" MODIFY ("ACCOUNTNUMBER" NOT NULL ENABLE);
  ALTER TABLE "MASTERBANK" MODIFY ("IFSCCODE" NOT NULL ENABLE);
  ALTER TABLE "MASTERBANK" MODIFY ("UANNUMBER" NOT NULL ENABLE);
  ALTER TABLE "MASTERBANK" MODIFY ("CREATEDDATE" NOT NULL ENABLE);
  ALTER TABLE "MASTERBANK" MODIFY ("CREATEDBY" NOT NULL ENABLE);
  ALTER TABLE "MASTERBANK" ADD PRIMARY KEY ("ID");
  ALTER TABLE "MASTERBANK" ADD UNIQUE ("EMPLOYEECODE");
--------------------------------------------------------
--  Constraints for Table MASTERCITY
--------------------------------------------------------

  ALTER TABLE "MASTERCITY" ADD CONSTRAINT "UC_CITYNAME" UNIQUE ("NAME");
  ALTER TABLE "MASTERCITY" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "MASTERCITY" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "MASTERCITY" MODIFY ("MASTERSTATEID" NOT NULL ENABLE);
  ALTER TABLE "MASTERCITY" MODIFY ("MASTERCITYCATEGORYID" NOT NULL ENABLE);
  ALTER TABLE "MASTERCITY" MODIFY ("CREATEDBY" NOT NULL ENABLE);
  ALTER TABLE "MASTERCITY" ADD PRIMARY KEY ("ID");
--------------------------------------------------------
--  Constraints for Table MASTERCITYCATEGORY
--------------------------------------------------------

  ALTER TABLE "MASTERCITYCATEGORY" MODIFY ("ISDELETED" NOT NULL ENABLE);
  ALTER TABLE "MASTERCITYCATEGORY" ADD CONSTRAINT "UC_MASTERCITYCATEGORY" UNIQUE ("NAME");
  ALTER TABLE "MASTERCITYCATEGORY" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "MASTERCITYCATEGORY" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "MASTERCITYCATEGORY" MODIFY ("HRA" NOT NULL ENABLE);
  ALTER TABLE "MASTERCITYCATEGORY" MODIFY ("MINHRA" NOT NULL ENABLE);
  ALTER TABLE "MASTERCITYCATEGORY" MODIFY ("ISACTIVE" NOT NULL ENABLE);
  ALTER TABLE "MASTERCITYCATEGORY" MODIFY ("CREATEDBY" NOT NULL ENABLE);
  ALTER TABLE "MASTERCITYCATEGORY" MODIFY ("CREATEDDATE" NOT NULL ENABLE);
  ALTER TABLE "MASTERCITYCATEGORY" ADD CHECK (IsActive IN (0, 1)) ENABLE;
  ALTER TABLE "MASTERCITYCATEGORY" ADD PRIMARY KEY ("ID");
--------------------------------------------------------
--  Constraints for Table MASTERDESIGNATION
--------------------------------------------------------

  ALTER TABLE "MASTERDESIGNATION" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "MASTERDESIGNATION" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "MASTERDESIGNATION" ADD PRIMARY KEY ("ID");
--------------------------------------------------------
--  Constraints for Table MASTEREMPLOYEE
--------------------------------------------------------

  ALTER TABLE "MASTEREMPLOYEE" ADD CONSTRAINT "UQ_MASTEREMPLOYEE_MOBILE" UNIQUE ("MOBILE");
  ALTER TABLE "MASTEREMPLOYEE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "MASTEREMPLOYEE" MODIFY ("EMPLOYEECODE" NOT NULL ENABLE);
  ALTER TABLE "MASTEREMPLOYEE" MODIFY ("FIRSTNAME" NOT NULL ENABLE);
  ALTER TABLE "MASTEREMPLOYEE" MODIFY ("GENDER" NOT NULL ENABLE);
  ALTER TABLE "MASTEREMPLOYEE" MODIFY ("DATEOFBIRTH" NOT NULL ENABLE);
  ALTER TABLE "MASTEREMPLOYEE" ADD CONSTRAINT "UQ_MASTEREMPLOYEE_EMAIL" UNIQUE ("EMAIL");
  ALTER TABLE "MASTEREMPLOYEE" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "MASTEREMPLOYEE" MODIFY ("MOBILE" NOT NULL ENABLE);
  ALTER TABLE "MASTEREMPLOYEE" MODIFY ("PANNO" NOT NULL ENABLE);
  ALTER TABLE "MASTEREMPLOYEE" MODIFY ("OFFICEID" NOT NULL ENABLE);
  ALTER TABLE "MASTEREMPLOYEE" MODIFY ("DATEOFJOINING" NOT NULL ENABLE);
  ALTER TABLE "MASTEREMPLOYEE" MODIFY ("DATEOFJOININGKVS" NOT NULL ENABLE);
  ALTER TABLE "MASTEREMPLOYEE" MODIFY ("DESIGNATIONID" NOT NULL ENABLE);
  ALTER TABLE "MASTEREMPLOYEE" ADD CONSTRAINT "UC_PAN" UNIQUE ("PANNO");
  ALTER TABLE "MASTEREMPLOYEE" MODIFY ("LEVELID" NOT NULL ENABLE);
  ALTER TABLE "MASTEREMPLOYEE" ADD PRIMARY KEY ("ID");
  ALTER TABLE "MASTEREMPLOYEE" ADD CONSTRAINT "UQ_EMPLOYEE_EMPLOYEECODE" UNIQUE ("EMPLOYEECODE");
--------------------------------------------------------
--  Constraints for Table MASTEREMPLOYEEROLE
--------------------------------------------------------

  ALTER TABLE "MASTEREMPLOYEEROLE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "MASTEREMPLOYEEROLE" MODIFY ("EMPLOYEECODE" NOT NULL ENABLE);
  ALTER TABLE "MASTEREMPLOYEEROLE" MODIFY ("ROLEID" NOT NULL ENABLE);
  ALTER TABLE "MASTEREMPLOYEEROLE" MODIFY ("CREATEDDATE" NOT NULL ENABLE);
  ALTER TABLE "MASTEREMPLOYEEROLE" ADD PRIMARY KEY ("ID");
--------------------------------------------------------
--  Constraints for Table MASTERLEAVE
--------------------------------------------------------

  ALTER TABLE "MASTERLEAVE" ADD CONSTRAINT "UNIQUE_LEAVE" UNIQUE ("LEAVETYPE");
  ALTER TABLE "MASTERLEAVE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "MASTERLEAVE" MODIFY ("LEAVETYPE" NOT NULL ENABLE);
  ALTER TABLE "MASTERLEAVE" MODIFY ("CAPDAYS" NOT NULL ENABLE);
  ALTER TABLE "MASTERLEAVE" MODIFY ("CREATEDDATE" NOT NULL ENABLE);
  ALTER TABLE "MASTERLEAVE" MODIFY ("CREATEDBY" NOT NULL ENABLE);
  ALTER TABLE "MASTERLEAVE" ADD PRIMARY KEY ("ID");
--------------------------------------------------------
--  Constraints for Table MASTERLEVEL
--------------------------------------------------------

  ALTER TABLE "MASTERLEVEL" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "MASTERLEVEL" MODIFY ("LEVELNAME" NOT NULL ENABLE);
  ALTER TABLE "MASTERLEVEL" MODIFY ("CREATEDDATE" NOT NULL ENABLE);
  ALTER TABLE "MASTERLEVEL" MODIFY ("CREATEDBY" NOT NULL ENABLE);
  ALTER TABLE "MASTERLEVEL" MODIFY ("ISACTIVE" NOT NULL ENABLE);
  ALTER TABLE "MASTERLEVEL" MODIFY ("ISDELETED" NOT NULL ENABLE);
  ALTER TABLE "MASTERLEVEL" ADD CONSTRAINT "UC_MASTERLEVEL" UNIQUE ("LEVELNAME");
--------------------------------------------------------
--  Constraints for Table MASTERLEVELBASICPAY
--------------------------------------------------------

  ALTER TABLE "MASTERLEVELBASICPAY" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "MASTERLEVELBASICPAY" MODIFY ("LEVELID" NOT NULL ENABLE);
  ALTER TABLE "MASTERLEVELBASICPAY" MODIFY ("PAYSCALE" NOT NULL ENABLE);
  ALTER TABLE "MASTERLEVELBASICPAY" MODIFY ("BASICPAY" NOT NULL ENABLE);
  ALTER TABLE "MASTERLEVELBASICPAY" MODIFY ("CREATEDDATE" NOT NULL ENABLE);
  ALTER TABLE "MASTERLEVELBASICPAY" MODIFY ("CREATEDBY" NOT NULL ENABLE);
  ALTER TABLE "MASTERLEVELBASICPAY" MODIFY ("ISACTIVE" NOT NULL ENABLE);
  ALTER TABLE "MASTERLEVELBASICPAY" MODIFY ("ISDELETED" NOT NULL ENABLE);
  ALTER TABLE "MASTERLEVELBASICPAY" ADD CONSTRAINT "UC_MASTERLEVELBASICPAY" UNIQUE ("LEVELID", "PAYSCALE", "BASICPAY");
--------------------------------------------------------
--  Constraints for Table MASTERMENU
--------------------------------------------------------

  ALTER TABLE "MASTERMENU" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "MASTERMENU" ADD PRIMARY KEY ("ID");
--------------------------------------------------------
--  Constraints for Table MASTERMODULE
--------------------------------------------------------

  ALTER TABLE "MASTERMODULE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "MASTERMODULE" ADD PRIMARY KEY ("ID");
--------------------------------------------------------
--  Constraints for Table MASTEROFFICE
--------------------------------------------------------

  ALTER TABLE "MASTEROFFICE" MODIFY ("DICOFFICETYPEID" NOT NULL ENABLE);
  ALTER TABLE "MASTEROFFICE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "MASTEROFFICE" MODIFY ("OFFICECODE" NOT NULL ENABLE);
  ALTER TABLE "MASTEROFFICE" MODIFY ("OFFICENAME" NOT NULL ENABLE);
  ALTER TABLE "MASTEROFFICE" ADD CONSTRAINT "MASTEROFFICE_PK" PRIMARY KEY ("ID");
  ALTER TABLE "MASTEROFFICE" ADD CONSTRAINT "OFFICECODE_UNIQUE" UNIQUE ("OFFICECODE");
--------------------------------------------------------
--  Constraints for Table MASTEROFFICE_BACKUP
--------------------------------------------------------

  ALTER TABLE "MASTEROFFICE_BACKUP" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "MASTEROFFICE_BACKUP" MODIFY ("OFFICECODE" NOT NULL ENABLE);
  ALTER TABLE "MASTEROFFICE_BACKUP" MODIFY ("OFFICENAME" NOT NULL ENABLE);
  ALTER TABLE "MASTEROFFICE_BACKUP" MODIFY ("DICOFFICETYPEID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MASTEROFFICE_BACKUP_02_04_2024
--------------------------------------------------------

  ALTER TABLE "MASTEROFFICE_BACKUP_02_04_2024" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "MASTEROFFICE_BACKUP_02_04_2024" MODIFY ("OFFICECODE" NOT NULL ENABLE);
  ALTER TABLE "MASTEROFFICE_BACKUP_02_04_2024" MODIFY ("OFFICENAME" NOT NULL ENABLE);
  ALTER TABLE "MASTEROFFICE_BACKUP_02_04_2024" MODIFY ("DICOFFICETYPEID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MASTEROFFICETYPE
--------------------------------------------------------

  ALTER TABLE "MASTEROFFICETYPE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "MASTEROFFICETYPE" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "MASTEROFFICETYPE" MODIFY ("CREATEDDATE" NOT NULL ENABLE);
  ALTER TABLE "MASTEROFFICETYPE" MODIFY ("CREATEDBY" NOT NULL ENABLE);
  ALTER TABLE "MASTEROFFICETYPE" ADD PRIMARY KEY ("ID");
  ALTER TABLE "MASTEROFFICETYPE" ADD UNIQUE ("TYPE");
--------------------------------------------------------
--  Constraints for Table MASTERPERMISSION
--------------------------------------------------------

  ALTER TABLE "MASTERPERMISSION" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "MASTERPERMISSION" ADD CONSTRAINT "PK_MASTERPERMISSION" PRIMARY KEY ("ID");
--------------------------------------------------------
--  Constraints for Table MASTERROLE
--------------------------------------------------------

  ALTER TABLE "MASTERROLE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "MASTERROLE" MODIFY ("ROLENAME" NOT NULL ENABLE);
  ALTER TABLE "MASTERROLE" MODIFY ("CREATEDBY" NOT NULL ENABLE);
  ALTER TABLE "MASTERROLE" MODIFY ("CREATEDDATE" NOT NULL ENABLE);
  ALTER TABLE "MASTERROLE" ADD PRIMARY KEY ("ID");
  ALTER TABLE "MASTERROLE" ADD CONSTRAINT "ROLENAME_UNIQUE" UNIQUE ("ROLENAME");
--------------------------------------------------------
--  Constraints for Table MASTERROLEPERMISSION
--------------------------------------------------------

  ALTER TABLE "MASTERROLEPERMISSION" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "MASTERROLEPERMISSION" ADD CONSTRAINT "PK_MASTERMENUROLEPERMISSION" PRIMARY KEY ("ID");
--------------------------------------------------------
--  Constraints for Table MASTERSTATE
--------------------------------------------------------

  ALTER TABLE "MASTERSTATE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "MASTERSTATE" MODIFY ("CODE" NOT NULL ENABLE);
  ALTER TABLE "MASTERSTATE" MODIFY ("STATENAME" NOT NULL ENABLE);
  ALTER TABLE "MASTERSTATE" MODIFY ("CREATEDDATE" NOT NULL ENABLE);
  ALTER TABLE "MASTERSTATE" MODIFY ("CREATEDBY" NOT NULL ENABLE);
  ALTER TABLE "MASTERSTATE" ADD PRIMARY KEY ("ID");
  ALTER TABLE "MASTERSTATE" ADD UNIQUE ("CODE");
  ALTER TABLE "MASTERSTATE" ADD CONSTRAINT "UC_STATENAME_MASTERSTATE" UNIQUE ("STATENAME");
--------------------------------------------------------
--  Constraints for Table MASTERTA
--------------------------------------------------------

  ALTER TABLE "MASTERTA" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "MASTERTA" ADD PRIMARY KEY ("ID");
--------------------------------------------------------
--  Constraints for Table MASTERTAXSLAB
--------------------------------------------------------

  ALTER TABLE "MASTERTAXSLAB" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "MASTERTAXSLAB" MODIFY ("MIN_INCOME" NOT NULL ENABLE);
  ALTER TABLE "MASTERTAXSLAB" MODIFY ("MAX_INCOME" NOT NULL ENABLE);
  ALTER TABLE "MASTERTAXSLAB" MODIFY ("TAX_RATE" NOT NULL ENABLE);
  ALTER TABLE "MASTERTAXSLAB" MODIFY ("CREATEDBY" NOT NULL ENABLE);
  ALTER TABLE "MASTERTAXSLAB" MODIFY ("CREATEDDATE" NOT NULL ENABLE);
  ALTER TABLE "MASTERTAXSLAB" ADD PRIMARY KEY ("ID");
--------------------------------------------------------
--  Constraints for Table PAYBILLALLOWANCE
--------------------------------------------------------

  ALTER TABLE "PAYBILLALLOWANCE" MODIFY ("HOUSERENTALLOWANCEDHRA" NOT NULL ENABLE);
  ALTER TABLE "PAYBILLALLOWANCE" MODIFY ("NPSMGTSHARE" NOT NULL ENABLE);
  ALTER TABLE "PAYBILLALLOWANCE" MODIFY ("CPFMGTSHARE" NOT NULL ENABLE);
  ALTER TABLE "PAYBILLALLOWANCE" MODIFY ("CASHHANDLINGTREASURYALLOWANCE" NOT NULL ENABLE);
  ALTER TABLE "PAYBILLALLOWANCE" MODIFY ("HIGHALTITUDEALLOWANCE" NOT NULL ENABLE);
  ALTER TABLE "PAYBILLALLOWANCE" MODIFY ("HARDAREAALLOWANCE" NOT NULL ENABLE);
  ALTER TABLE "PAYBILLALLOWANCE" MODIFY ("ISLANDSPECIALDUTYALLOWANCE" NOT NULL ENABLE);
  ALTER TABLE "PAYBILLALLOWANCE" MODIFY ("SPECIALDUTYALLOWANCE" NOT NULL ENABLE);
  ALTER TABLE "PAYBILLALLOWANCE" MODIFY ("TOUGHLOCATIONALLOWANCE1" NOT NULL ENABLE);
  ALTER TABLE "PAYBILLALLOWANCE" MODIFY ("TOUGHLOCATIONALLOWANCE2" NOT NULL ENABLE);
  ALTER TABLE "PAYBILLALLOWANCE" MODIFY ("TOUGHLOCATIONALLOWANCE3" NOT NULL ENABLE);
  ALTER TABLE "PAYBILLALLOWANCE" MODIFY ("SECONDSHIFTALLOWANCE" NOT NULL ENABLE);
  ALTER TABLE "PAYBILLALLOWANCE" MODIFY ("OTHERALLOWANCE" NOT NULL ENABLE);
  ALTER TABLE "PAYBILLALLOWANCE" MODIFY ("DRESSALLOWANCE" NOT NULL ENABLE);
  ALTER TABLE "PAYBILLALLOWANCE" MODIFY ("CREATEDDATE" NOT NULL ENABLE);
  ALTER TABLE "PAYBILLALLOWANCE" MODIFY ("CREATEDBY" NOT NULL ENABLE);
  ALTER TABLE "PAYBILLALLOWANCE" ADD PRIMARY KEY ("ID");
  ALTER TABLE "PAYBILLALLOWANCE" MODIFY ("DAONTRANSPORTALL0WANCE" NOT NULL ENABLE);
  ALTER TABLE "PAYBILLALLOWANCE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "PAYBILLALLOWANCE" MODIFY ("PAYBILLEMPLOYEEID" NOT NULL ENABLE);
  ALTER TABLE "PAYBILLALLOWANCE" MODIFY ("DEPUTATIONALLOWANCE" NOT NULL ENABLE);
  ALTER TABLE "PAYBILLALLOWANCE" MODIFY ("DEARNESSALLOWANCE" NOT NULL ENABLE);
  ALTER TABLE "PAYBILLALLOWANCE" MODIFY ("TRANSPORTALLOWANCE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PAYBILLDEDUCTION
--------------------------------------------------------

  ALTER TABLE "PAYBILLDEDUCTION" MODIFY ("PAYBILLEMPLOYEEID" NOT NULL ENABLE);
  ALTER TABLE "PAYBILLDEDUCTION" MODIFY ("INCOMETAX" NOT NULL ENABLE);
  ALTER TABLE "PAYBILLDEDUCTION" MODIFY ("PROFESSIONALTAX" NOT NULL ENABLE);
  ALTER TABLE "PAYBILLDEDUCTION" MODIFY ("LICENCEFEEOUTSIDEAGENCY" NOT NULL ENABLE);
  ALTER TABLE "PAYBILLDEDUCTION" MODIFY ("ELECTRICWATERCHARGESOUTSIDEAGENCY" NOT NULL ENABLE);
  ALTER TABLE "PAYBILLDEDUCTION" MODIFY ("NPSOWNSHARE" NOT NULL ENABLE);
  ALTER TABLE "PAYBILLDEDUCTION" MODIFY ("NPSMGTSHARE" NOT NULL ENABLE);
  ALTER TABLE "PAYBILLDEDUCTION" MODIFY ("COOPSOCIETY" NOT NULL ENABLE);
  ALTER TABLE "PAYBILLDEDUCTION" MODIFY ("CONVADVINTERESTRECOVERY" NOT NULL ENABLE);
  ALTER TABLE "PAYBILLDEDUCTION" MODIFY ("CAIRINSTALLMENTNO" NOT NULL ENABLE);
  ALTER TABLE "PAYBILLDEDUCTION" MODIFY ("HOUSEBUILDINGADVANCEINTEREST" NOT NULL ENABLE);
  ALTER TABLE "PAYBILLDEDUCTION" MODIFY ("HBAIINSTALLMENTNO" NOT NULL ENABLE);
  ALTER TABLE "PAYBILLDEDUCTION" MODIFY ("PRIMEMINISTERCARESFUND" NOT NULL ENABLE);
  ALTER TABLE "PAYBILLDEDUCTION" MODIFY ("OTHERREMITTANCES" NOT NULL ENABLE);
  ALTER TABLE "PAYBILLDEDUCTION" MODIFY ("GPFRECOVERY" NOT NULL ENABLE);
  ALTER TABLE "PAYBILLDEDUCTION" MODIFY ("GPFADVANCERECOVERY" NOT NULL ENABLE);
  ALTER TABLE "PAYBILLDEDUCTION" MODIFY ("GPFINSTALMENTNO" NOT NULL ENABLE);
  ALTER TABLE "PAYBILLDEDUCTION" MODIFY ("CPFRECOVERYOWNSHARE" NOT NULL ENABLE);
  ALTER TABLE "PAYBILLDEDUCTION" MODIFY ("CPFRECOVERYMGTSHARE" NOT NULL ENABLE);
  ALTER TABLE "PAYBILLDEDUCTION" MODIFY ("CPFADVRECOVERY" NOT NULL ENABLE);
  ALTER TABLE "PAYBILLDEDUCTION" MODIFY ("KVSEMPLOYEESWELFARESCHEME" NOT NULL ENABLE);
  ALTER TABLE "PAYBILLDEDUCTION" MODIFY ("HPLRECOVERY" NOT NULL ENABLE);
  ALTER TABLE "PAYBILLDEDUCTION" MODIFY ("LICENCEFEESKVSBUILDING" NOT NULL ENABLE);
  ALTER TABLE "PAYBILLDEDUCTION" MODIFY ("ELECTRICWATERCHARGES" NOT NULL ENABLE);
  ALTER TABLE "PAYBILLDEDUCTION" MODIFY ("RECOFOVERPAYMENT" NOT NULL ENABLE);
  ALTER TABLE "PAYBILLDEDUCTION" MODIFY ("CGHSRECOVERY" NOT NULL ENABLE);
  ALTER TABLE "PAYBILLDEDUCTION" MODIFY ("OTHERDEDUCTIONS" NOT NULL ENABLE);
  ALTER TABLE "PAYBILLDEDUCTION" MODIFY ("CREATEDDATE" NOT NULL ENABLE);
  ALTER TABLE "PAYBILLDEDUCTION" MODIFY ("CREATEDBY" NOT NULL ENABLE);
  ALTER TABLE "PAYBILLDEDUCTION" ADD PRIMARY KEY ("ID");
  ALTER TABLE "PAYBILLDEDUCTION" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PAYBILLEMPLOYEE
--------------------------------------------------------

  ALTER TABLE "PAYBILLEMPLOYEE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "PAYBILLEMPLOYEE" MODIFY ("PAYBILLMAINID" NOT NULL ENABLE);
  ALTER TABLE "PAYBILLEMPLOYEE" MODIFY ("EMPLOYEECODE" NOT NULL ENABLE);
  ALTER TABLE "PAYBILLEMPLOYEE" MODIFY ("EMPLOYEENAME" NOT NULL ENABLE);
  ALTER TABLE "PAYBILLEMPLOYEE" MODIFY ("EMPLOYEEDESIGNATION" NOT NULL ENABLE);
  ALTER TABLE "PAYBILLEMPLOYEE" MODIFY ("LEVELNAME" NOT NULL ENABLE);
  ALTER TABLE "PAYBILLEMPLOYEE" MODIFY ("TOTALDAYS" NOT NULL ENABLE);
  ALTER TABLE "PAYBILLEMPLOYEE" MODIFY ("TOTALPRESENTDAYS" NOT NULL ENABLE);
  ALTER TABLE "PAYBILLEMPLOYEE" MODIFY ("BASICPAY" NOT NULL ENABLE);
  ALTER TABLE "PAYBILLEMPLOYEE" MODIFY ("TOTALALLOWANCE" NOT NULL ENABLE);
  ALTER TABLE "PAYBILLEMPLOYEE" MODIFY ("TOTALDEDUCTION" NOT NULL ENABLE);
  ALTER TABLE "PAYBILLEMPLOYEE" MODIFY ("FINALAMOUNT" NOT NULL ENABLE);
  ALTER TABLE "PAYBILLEMPLOYEE" MODIFY ("CREATEDDATE" NOT NULL ENABLE);
  ALTER TABLE "PAYBILLEMPLOYEE" MODIFY ("CREATEDBY" NOT NULL ENABLE);
  ALTER TABLE "PAYBILLEMPLOYEE" ADD PRIMARY KEY ("ID");
--------------------------------------------------------
--  Constraints for Table PAYBILLMAIN
--------------------------------------------------------

  ALTER TABLE "PAYBILLMAIN" ADD CONSTRAINT "PAYBILLMAIN_PK" PRIMARY KEY ("ID");
  ALTER TABLE "PAYBILLMAIN" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "PAYBILLMAIN" MODIFY ("OFFICECODE" NOT NULL ENABLE);
  ALTER TABLE "PAYBILLMAIN" MODIFY ("MONTH" NOT NULL ENABLE);
  ALTER TABLE "PAYBILLMAIN" MODIFY ("YEAR" NOT NULL ENABLE);
  ALTER TABLE "PAYBILLMAIN" MODIFY ("CREATEDDATE" NOT NULL ENABLE);
  ALTER TABLE "PAYBILLMAIN" MODIFY ("CREATEDBY" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table LEAVEENTRY
--------------------------------------------------------

  ALTER TABLE "LEAVEENTRY" ADD CONSTRAINT "FK_LEAVEENTRY_LEAVEENTRYMAIN" FOREIGN KEY ("LEAVEENTRYMAINID")
	  REFERENCES "LEAVEENTRYMAIN" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MASTERADDRESS
--------------------------------------------------------

  ALTER TABLE "MASTERADDRESS" ADD CONSTRAINT "FK_ADDRESS_STATE" FOREIGN KEY ("STATEID")
	  REFERENCES "MASTERSTATE" ("ID") ENABLE;
  ALTER TABLE "MASTERADDRESS" ADD CONSTRAINT "FK_ADDRESS_CITY" FOREIGN KEY ("CITYID")
	  REFERENCES "MASTERCITY" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MASTERBANK
--------------------------------------------------------

  ALTER TABLE "MASTERBANK" ADD CONSTRAINT "FK_BANK_CITY" FOREIGN KEY ("BANKCITYID")
	  REFERENCES "MASTERCITY" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MASTEREMPLOYEE
--------------------------------------------------------

  ALTER TABLE "MASTEREMPLOYEE" ADD CONSTRAINT "FK_EMPLOYEE_MASTERDESIGNATION" FOREIGN KEY ("DESIGNATIONID")
	  REFERENCES "MASTERDESIGNATION" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "MASTEREMPLOYEE" ADD CONSTRAINT "FK_EMPLOYEE_MASTEROFFICE" FOREIGN KEY ("OFFICEID")
	  REFERENCES "MASTEROFFICE" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PAYBILLALLOWANCE
--------------------------------------------------------

  ALTER TABLE "PAYBILLALLOWANCE" ADD CONSTRAINT "FK_PAYBILLALLOWANCE_PAYBILLEMPLOYEE" FOREIGN KEY ("PAYBILLEMPLOYEEID")
	  REFERENCES "PAYBILLEMPLOYEE" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PAYBILLDEDUCTION
--------------------------------------------------------

  ALTER TABLE "PAYBILLDEDUCTION" ADD CONSTRAINT "FK_PAYBILLDEDUCTION_PAYBILLEMPLOYEE" FOREIGN KEY ("PAYBILLEMPLOYEEID")
	  REFERENCES "PAYBILLEMPLOYEE" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PAYBILLEMPLOYEE
--------------------------------------------------------

  ALTER TABLE "PAYBILLEMPLOYEE" ADD CONSTRAINT "FK_PAYBILLEMPLOYEE_PAYBILLMAIN" FOREIGN KEY ("PAYBILLMAINID")
	  REFERENCES "PAYBILLMAIN" ("ID") ENABLE;
