
----------------MASTERCITY------

INSERT INTO MASTERCITY(NAME,MASTERSTATEID,MASTERCITYCATEGORYID,ADDITIONALHRA,ISACTIVE,CREATEDBY,CREATEDDATE,ISDELETED)
SELECT CITY,MASTERSTATEID,22,0,1,'Manual',CURRENT_TIMESTAMP,0 FROM
(SELECT DISTINCT CITY, B.ID AS MASTERSTATEID FROM TEMP_MASTEROFFICE A
INNER JOIN MASTERSTATE B ON A.STATE=B.STATENAME
WHERE LOWER(CITY) NOT IN (SELECT DISTINCT LOWER(NAME) FROM MASTERCITY)
);
----------MASTERADDRESS REGION------

INSERT INTO MasterAddress (TABLEKEY, TABLENAME, ADDRESS1, ADDRESS2, CITYID, STATEID, PIN, CREATEDBY, CREATEDDATE, ISDELETED, CITY, OFFICECODE)
SELECT F.ID, 'MASTEROFFICE', '', '', C.Id, C.MASTERSTATEID, PINCODE, 'Manual', CURRENT_TIMESTAMP, 0, C.NAME, F.OFFICECODE
FROM MASTEROFFICE F
JOIN TEMP_MASTEROFFICE F1 ON F1.OFFICECODE = F.OFFICECODE
JOIN MASTERCITY C ON C.NAME = F1.CITY;

-------REGION CITIES----

SELECT REGION AS CITY, STATE AS MASTERSTATEID,22,0,1,'Manual',current_timestamp,0 FROM TEMP_STATE A
INNER JOIN MASTERSTATE B ON A.STATE=B.ID
WHERE LOWER(REGION) NOT IN (SELECT DISTINCT LOWER(NAME) FROM MASTERCITY);


----------MASTERADDRESS REGION------

INSERT INTO MasterAddress (TABLEKEY, TABLENAME, ADDRESS1, ADDRESS2, CITYID, STATEID, PIN, CREATEDBY, CREATEDDATE, ISDELETED, CITY, OFFICECODE)
SELECT F.ID, 'MASTEROFFICE', '', '', C.Id, C.MASTERSTATEID, null, 'Manual', CURRENT_TIMESTAMP, 0, C.NAME, F.OFFICECODE
FROM MASTEROFFICE F
JOIN MASTERCITY C ON upper(C.NAME) = upper(F.officename)
--WHERE upper(c.name) in (select region from temp_state)
;
